/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    blogs: Blog;
    jobs: Job;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'social-links': SocialLink;
  };
  globalsSelect: {
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Lower numbers appear first
   */
  order: number;
  name: string;
  description: string;
  thumbnail: number | Media;
  github?: string | null;
  view?: string | null;
  technologies?:
    | (
        | 'TypeScript'
        | 'JavaScript'
        | 'Python'
        | 'Golang'
        | 'Rust'
        | 'Java'
        | 'C'
        | 'C++'
        | 'C#'
        | 'PHP'
        | 'Ruby'
        | 'Swift'
        | 'Kotlin'
        | 'Bash'
        | 'PowerShell'
        | 'R'
        | 'Scala'
        | 'Dart'
        | 'Elixir'
        | 'Haskell'
        | 'Lua'
        | 'MATLAB'
        | 'React'
        | 'Next.js'
        | 'Vue.js'
        | 'Nuxt.js'
        | 'Svelte'
        | 'SvelteKit'
        | 'Angular'
        | 'Astro'
        | 'Remix'
        | 'HTMX'
        | 'Tailwind CSS'
        | 'Sass'
        | 'Node.js'
        | 'Express'
        | 'Fastify'
        | 'NestJS'
        | 'Django'
        | 'Flask'
        | 'FastAPI'
        | 'Rails'
        | 'Laravel'
        | 'Spring Boot'
        | 'ASP.NET'
        | 'Gin'
        | 'Fiber'
        | 'Phoenix'
        | 'PostgreSQL'
        | 'MySQL'
        | 'SQLite'
        | 'MongoDB'
        | 'Redis'
        | 'Elasticsearch'
        | 'DynamoDB'
        | 'Supabase'
        | 'PlanetScale'
        | 'CockroachDB'
        | 'Cassandra'
        | 'InfluxDB'
        | 'Docker'
        | 'Kubernetes'
        | 'AWS'
        | 'Google Cloud'
        | 'Azure'
        | 'Terraform'
        | 'Ansible'
        | 'GitHub Actions'
        | 'GitLab CI'
        | 'Jenkins'
        | 'Nginx'
        | 'Caddy'
        | 'Cloudflare'
        | 'Vercel'
        | 'Netlify'
        | 'Railway'
        | 'Fly.io'
        | 'React Native'
        | 'Flutter'
        | 'Expo'
        | 'SwiftUI'
        | 'Jetpack Compose'
        | 'TensorFlow'
        | 'PyTorch'
        | 'LangChain'
        | 'OpenAI API'
        | 'Hugging Face'
        | 'scikit-learn'
        | 'GraphQL'
        | 'REST'
        | 'gRPC'
        | 'WebSockets'
        | 'Prisma'
        | 'Drizzle'
        | 'Payload CMS'
        | 'Strapi'
        | 'WordPress'
        | 'Storybook'
        | 'Vite'
        | 'Webpack'
        | 'Turborepo'
        | 'pnpm'
        | 'Linux'
        | 'Git'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  /**
   * Lower numbers appear first
   */
  order: number;
  title: string;
  description: string;
  thumbnail: number | Media;
  view?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  /**
   * Lower numbers appear first
   */
  order: number;
  company: string;
  title: string;
  startDate: string;
  endDate: string;
  technologies?:
    | (
        | 'TypeScript'
        | 'JavaScript'
        | 'Python'
        | 'Golang'
        | 'Rust'
        | 'Java'
        | 'C'
        | 'C++'
        | 'C#'
        | 'PHP'
        | 'Ruby'
        | 'Swift'
        | 'Kotlin'
        | 'Bash'
        | 'PowerShell'
        | 'R'
        | 'Scala'
        | 'Dart'
        | 'Elixir'
        | 'Haskell'
        | 'Lua'
        | 'MATLAB'
        | 'React'
        | 'Next.js'
        | 'Vue.js'
        | 'Nuxt.js'
        | 'Svelte'
        | 'SvelteKit'
        | 'Angular'
        | 'Astro'
        | 'Remix'
        | 'HTMX'
        | 'Tailwind CSS'
        | 'Sass'
        | 'Node.js'
        | 'Express'
        | 'Fastify'
        | 'NestJS'
        | 'Django'
        | 'Flask'
        | 'FastAPI'
        | 'Rails'
        | 'Laravel'
        | 'Spring Boot'
        | 'ASP.NET'
        | 'Gin'
        | 'Fiber'
        | 'Phoenix'
        | 'PostgreSQL'
        | 'MySQL'
        | 'SQLite'
        | 'MongoDB'
        | 'Redis'
        | 'Elasticsearch'
        | 'DynamoDB'
        | 'Supabase'
        | 'PlanetScale'
        | 'CockroachDB'
        | 'Cassandra'
        | 'InfluxDB'
        | 'Docker'
        | 'Kubernetes'
        | 'AWS'
        | 'Google Cloud'
        | 'Azure'
        | 'Terraform'
        | 'Ansible'
        | 'GitHub Actions'
        | 'GitLab CI'
        | 'Jenkins'
        | 'Nginx'
        | 'Caddy'
        | 'Cloudflare'
        | 'Vercel'
        | 'Netlify'
        | 'Railway'
        | 'Fly.io'
        | 'React Native'
        | 'Flutter'
        | 'Expo'
        | 'SwiftUI'
        | 'Jetpack Compose'
        | 'TensorFlow'
        | 'PyTorch'
        | 'LangChain'
        | 'OpenAI API'
        | 'Hugging Face'
        | 'scikit-learn'
        | 'GraphQL'
        | 'REST'
        | 'gRPC'
        | 'WebSockets'
        | 'Prisma'
        | 'Drizzle'
        | 'Payload CMS'
        | 'Strapi'
        | 'WordPress'
        | 'Storybook'
        | 'Vite'
        | 'Webpack'
        | 'Turborepo'
        | 'pnpm'
        | 'Linux'
        | 'Git'
      )[]
    | null;
  accomplishments: string[];
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  order?: T;
  name?: T;
  description?: T;
  thumbnail?: T;
  github?: T;
  view?: T;
  technologies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  description?: T;
  thumbnail?: T;
  view?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  order?: T;
  company?: T;
  title?: T;
  startDate?: T;
  endDate?: T;
  technologies?: T;
  accomplishments?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  /**
   * Enter your LinkedIn username (e.g., "yourprofile" from linkedin.com/in/yourprofile)
   */
  linkedin?: string | null;
  /**
   * Enter your GitHub username (e.g., "yourusername" from github.com/yourusername)
   */
  github?: string | null;
  /**
   * Enter your Twitter/X username (e.g., "yourusername" from x.com/yourusername)
   */
  twitter?: string | null;
  email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  linkedin?: T;
  github?: T;
  twitter?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}